Polish graphs shown after game
ErikLundb3rg/typebout pull request #62
Opened 2023-05-13 01:58 UTC by jonatan-kruse

This uses a new, in my opinion better wpm history that is not as weird and jagged. we should probably remove the old wpm history if we go for this aproach,

This commit also adds the ability to see "raw wpm" wich basically is the wpm for the latest 3 words only instead of the wpm for the entire quote

2023-05-13 17:58 UTC, ErikLundb3rg requested changes
See comments. How did you figure out the value for lookback?  That is a parameter we might want to teak, I assume a smaller value means greater variance and vice versa. 

I had an issue with the axis and graphs looking like this: 
![image](https://github.com/ErikLundb3rg/typebout/assets/56272948/8d0e9232-5be4-4970-b907-81ee65642f3f)

Otherwise I think this feature would be a great addition 🌟

2023-05-13 17:58 UTC, ErikLundb3rg commented on frontend/src/components/PostGameStats.tsx
> +  const wpmHistory = chosenEndgameStats.wpmHistory.map((wpm) => wpm.wpm)
`wpmHistory` is redundant, just an extra variable. We can instead always use `wpmHistoryTime`

2023-05-13 17:58 UTC, ErikLundb3rg commented on backend/src/game/logic/gameDirector.ts
> +  private wpmHistory: { wpm: number, time: number }[] = []
`time` here as a a number is a bit ambiguous. Calling it something like `elapsedSeconds` feels a bit more descriptive.

2023-05-13 17:58 UTC, ErikLundb3rg commented on backend/src/game/logic/gameDirector.ts
> +    this.wpmHistory.push({ wpm: this.getWPM(), time: (Date.now() - (this.startTime ?? 0)) })
using non-null assertion operator as `!this.startTime` can be used instead of `this.startTime ?? 0`

2023-05-13 17:58 UTC, ErikLundb3rg commented on backend/src/game/types/index.ts
> +// Information about the game sent continuously
🔥 🔥 🔥 🔥 🔥

2023-05-13 17:58 UTC, ErikLundb3rg commented on frontend/src/components/PostGameStats.tsx
> +    const words = wpm * time
Here `words`  gets confusing as `time` is in seconds and thus `words` is actually 60 times the amount of words typed... 

It works because we just calculate the difference, but the calculation gets confusing.

2023-05-13 18:01 UTC, jonatan-kruse commented on backend/src/game/logic/gameDirector.ts
> +    this.wpmHistory.push({ wpm: this.getWPM(), time: (Date.now() - (this.startTime ?? 0)) })
what do you mean? Why and where do you wan't me to do this? null check and do nothing if it's null?

2023-05-13 18:03 UTC, jonatan-kruse commented on frontend/src/components/PostGameStats.tsx
> +    const words = wpm * time
Noticed this while writing but I did not think it was logical to change it into actual "words" just for semantic reasons, maybe some better naming can be used

2023-05-13 18:06 UTC, jonatan-kruse commented on frontend/src/components/PostGameStats.tsx
> +  })
I see what you mean but it somehow makes sense in my head to send the data from the backend and chose what to do with it in our visualisations on the frontend. the backend should not be concerned with what type of visualisations we want on the frontend as long as the correct data is beeing sent.

Wont slow down performance and is cheaper for you also to do some of the data transformation on the frontend

2023-05-13 18:08 UTC, ErikLundb3rg commented on frontend/src/components/PostGameStats.tsx
> +    const words = wpm * time
Yeah the problem here for me is that it is named as something it is not.

2023-05-13 18:10 UTC, ErikLundb3rg commented on backend/src/game/logic/gameDirector.ts
> +    this.wpmHistory.push({ wpm: this.getWPM(), time: (Date.now() - (this.startTime ?? 0)) })
My bad, wrote it wrong I meant `this.startTime!` so    
     `this.wpmHistory.push({ wpm: this.getWPM(), time: (Date.now() - (this.startTime ?? 0)) })`
to
     `this.wpmHistory.push({ wpm: this.getWPM(), time: (Date.now() - this.startTime!) })`

2023-05-13 18:16 UTC, ErikLundb3rg commented on frontend/src/components/PostGameStats.tsx
> +  })
Business logic should be done in the backend and this is only sent once to users after finishing their game, it wont really impact performance. Having `rawWpmHistory` be calculated from `wpmHistoryTime` in the client just increases complexity. Also I wouldn't call `rawWpmHistory` just a visualization which the backend shouldn't be concerned about, it is a relevant metric for the user which is part of the game just like any other stat.

2023-05-13 18:22 UTC, jonatan-kruse commented on frontend/src/components/PostGameStats.tsx
> +  })
feels redundant to send basically the same data twice just in different formats and unnecessary to have to change the backend and it's API every time we want the data in a slightly different format.

 Will change this to be calculated in the backend for now.

2023-05-17 12:22 UTC, ErikLundb3rg approved these changes

2023-05-17 12:23 UTC, merged