Update profile graph and data
ErikLundb3rg/typebout pull request #70
Opened 2023-06-17 19:11 UTC by jonatan-kruse

Bara approva denna det ser så mycket bättre ut och ger så mycket bättre information för användaren, hur långt skulle ett commit message vara nu igen för jag tror jag har glömt bort

2023-06-19 18:52 UTC, ErikLundb3rg requested changes
I think this will be a great feature! 

See comments.

2023-06-19 18:52 UTC, ErikLundb3rg commented on backend/src/dal/performances.ts
> +  entries?: number
What happens if this is undefined, will all entries be returned?

2023-06-19 18:52 UTC, ErikLundb3rg commented on frontend/src/app/users/profile/page.tsx
> +    }
This fallback is a bit clunky. I think we could do non null assertion operator instead using: 
`data!.data`
You probably have to check for `error` before accessing the `data.data` property if we go that way.

2023-06-19 18:52 UTC, ErikLundb3rg commented on frontend/src/app/users/profile/page.tsx
> +  console.log(wpmHistory)
Nice useMemo! However: 

Are you sure the lastRaces logic here is working, slicing takes from start to end and lastRaces is in descending order. So last10Races is actually oldest10races.

Also remove the console.log()

2023-06-19 18:52 UTC, ErikLundb3rg commented on frontend/src/app/users/profile/page.tsx
> +                </Box>
Looks nice, have you tested that this change is responsive?

2023-06-19 18:52 UTC, ErikLundb3rg commented on frontend/src/app/users/profile/page.tsx
> +  console.log(last10)
Remove console.log() here

2023-06-19 18:52 UTC, ErikLundb3rg commented on frontend/src/app/users/profile/page.tsx
> +  }, [wpmHistory])
No need to change but fyi you can do ``` useMemo(() => wpmHistory.slice(Math.max(wpmHistory.length - 10, 0)))``` instead and skip the curly brackets.

2023-06-19 18:52 UTC, ErikLundb3rg commented on frontend/src/components/performancesTable.tsx
> +  const { data, error, isLoading } = useSWR(path, (url) => fetcherGet<any>(url))
Do you have to pass a type parameter here? I thought Typescript would default to `any`? Did it complain before?

2023-06-19 21:17 UTC, jonatan-kruse commented on backend/src/dal/performances.ts
> +  entries?: number
Yes according to the definition of take is undefined it returns all. This is why you can send a request without the argument being defined and then it returns all elements.

2023-06-19 21:18 UTC, jonatan-kruse commented on frontend/src/app/users/profile/page.tsx
> +    }
We cannot check for null before since that would trigger a conditioned hook which is not allowed in react

2023-06-19 21:51 UTC, jonatan-kruse commented on frontend/src/app/users/profile/page.tsx
> +    }
Agreed that this is not a nice solution and I'm open for ideas on how to make it cleaner

2023-06-19 21:59 UTC, jonatan-kruse commented on frontend/src/components/performancesTable.tsx
> +  const { data, error, isLoading } = useSWR(path, (url) => fetcherGet<any>(url))
It defaults to unknown, the reason it worked before is that there was no type parameter. 

This should ofc not be any type but only fixed the type for the code I was working on

2023-06-27 20:49 UTC, jonatan-kruse commented on frontend/src/app/users/profile/page.tsx
> +    }
fixed it now :))

2023-06-27 20:49 UTC, jonatan-kruse commented on frontend/src/app/users/profile/page.tsx
> +  console.log(wpmHistory)
fixed!

2023-06-27 20:50 UTC, jonatan-kruse commented on frontend/src/app/users/profile/page.tsx
> +                </Box>
yep, try it yourself if you want

2023-07-03 13:16 UTC, ErikLundb3rg approved these changes
Nice, approved!

2023-07-03 13:16 UTC, merged